(function () {
  const CFG = window.PIXEL_CONFIG;
  const STORAGE_KEY = "pixel11-reserve";
  const MAX_ITEMS = 2;

  const I18N = {
    en: {
      home: "home",
      how: "how",
      sale: "pixel 11",
      macMini: "mac mini",
      garage: "garage",
      blog: "blog",
      reviews: "reviews",
      shop: "shop",
      title: "Pixel 11 Series",
      intro: "sealed pixel 11 from singapore. official google store sgd. tap i next to the ask if you want the math. jakarta pickup or courier.",
      filterAll: "all",
      filter11: "pixel 11",
      filterPro: "pro",
      filterXl: "pro xl",
      filterFold: "fold",
      add: "add",
      inBag: "in bag",
      bag: "bag",
      checkout: "checkout",
      pay: "pay",
      reserve: "add",
      reserved: "in bag",
      continue: "checkout",
      drawerTitle: "bag",
      cancel: "close",
      success: "paid. i'll ping you on x or linkedin about delivery.",
      error: "couldn't start checkout. try again?",
      paySoon: "pay isn't live yet. stripe key still missing.",
      total: "total",
      itemAdded: "{n} in bag",
      itemsAdded: "{n} in bag",
      howTitle: "how this works",
      howBody: [
        "ask is built from official google store singapore, not ishopchangi. 256 gb list: pixel 11 s$1,299, pro s$1,599, pro xl s$1,819, fold s$2,499. higher storage is +s$200 a step.",
        "for 1 phone: official minus 9% gst, minus usd 500 pib, then bm 10% and ppn 11% on the rest (ppn sits on value + bm), plus rp 5.000.000 markup. my take is the gst refund plus that markup.",
        "two phones on one trip share the usd 500 exemption — ping me and i'll recompute.",
        "add a color and storage (max 2), then pay with card, apple pay, or google pay. i'll ping you on x or linkedin about delivery."
      ],
      contactTitle: "contact",
      contactBody: "dm me on x or linkedin.",
      footerIshop: "google store sg",
      priceInfo: "how this price is built",
      officialLabel: "official",
      askLabel: "ask"
    },
    id: {
      home: "home",
      how: "cara",
      sale: "pixel 11",
      macMini: "mac mini",
      garage: "garage",
      blog: "blog",
      reviews: "reviews",
      shop: "shop",
      title: "Pixel 11 Series",
      intro: "pixel 11 sealed dari singapura. harga resmi google store sg. ketuk i di samping ask kalau mau lihat hitungannya. ambil jakarta atau kurir.",
      filterAll: "semua",
      filter11: "pixel 11",
      filterPro: "pro",
      filterXl: "pro xl",
      filterFold: "fold",
      add: "add",
      inBag: "in bag",
      bag: "bag",
      checkout: "checkout",
      pay: "pay",
      reserve: "add",
      reserved: "in bag",
      continue: "checkout",
      drawerTitle: "bag",
      cancel: "tutup",
      success: "sudah bayar. saya hubungi di x atau linkedin soal pengiriman.",
      error: "checkout gagal. coba lagi?",
      paySoon: "pay belum hidup. kunci stripe belum dipasang.",
      total: "total",
      itemAdded: "{n} in bag",
      itemsAdded: "{n} in bag",
      howTitle: "cara kerjanya",
      howBody: [
        "ask dari harga resmi google store singapura, bukan ishopchangi. 256 gb: pixel 11 s$1.299, pro s$1.599, pro xl s$1.819, fold s$2.499. storage lebih besar +s$200.",
        "untuk 1 hp: resmi minus gst 9%, minus pib usd 500, lalu bm 10% dan ppn 11% dari sisa (ppn dihitung dari nilai + bm), plus markup rp 5.000.000. untung saya = refund gst + markup itu.",
        "dua hp dalam satu trip berbagi pib usd 500 — chat, saya hitung ulang.",
        "masukkan warna dan penyimpanan (maks 2), lalu bayar dengan kartu, apple pay, atau google pay. saya hubungi di x atau linkedin soal pengiriman."
      ],
      contactTitle: "kontak",
      contactBody: "dm saya di x atau linkedin.",
      footerIshop: "google store sg",
      priceInfo: "cara harga ini disusun",
      officialLabel: "resmi",
      askLabel: "ask"
    }
  };
